"""Strict structured output schemas for VibeControl zapping analysis."""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


class ZappingAnalysisRole(BaseModel):
    model_config = ConfigDict(extra="forbid")

    value: str = Field(min_length=1)
    grounding: Literal["explicit", "inferred"] = "inferred"


class ZappingAnalysisEvidence(BaseModel):
    model_config = ConfigDict(extra="forbid")

    videoId: str = Field(min_length=1)
    title: str = Field(
        min_length=1,
        description="Short label for this evidence segment.",
    )
    summary: str = Field(
        min_length=1,
        description="What is happening in this video segment.",
    )
    tRange: list[float] = Field(
        description="Two numbers in seconds: [start, end].",
    )
    representativeScreenshotId: str = Field(
        min_length=1,
        description="The single best screenshot id for this segment.",
    )
    screenshotIds: list[str] = Field(min_length=1)
    transcriptCueIds: list[str] = Field(
        min_length=1,
        description="Timestamped transcript cue ids that ground this evidence.",
    )
    transcriptQuote: str = Field(
        min_length=1,
        description="Short quote from the timestamped transcript for this evidence.",
    )

    @field_validator("tRange")
    @classmethod
    def validate_t_range(cls, value: list[float]) -> list[float]:
        if len(value) != 2:
            raise ValueError("tRange must contain exactly two numbers: [start, end].")
        start, end = value
        if start < 0 or end < 0:
            raise ValueError("tRange values must be greater than or equal to 0.")
        if end < start:
            raise ValueError("tRange end must be greater than or equal to start.")
        return value


class ZappingAnalysisStoryCandidate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    id: str = Field(min_length=1)
    epicId: str | None = None
    title: str = Field(min_length=1)
    role: ZappingAnalysisRole
    goal: str = Field(min_length=1)
    benefit: str = Field(min_length=1)
    acceptanceCriteria: list[str] = Field(min_length=1)
    summary: str | None = None
    userStory: str | None = None
    asA: str | None = None
    iWant: str | None = None
    soThat: str | None = None
    evidence: list[ZappingAnalysisEvidence] = Field(min_length=1)
    unverified: bool = False
    confidenceScore: int = Field(ge=0, le=100)
    confidence: int | None = Field(default=None, ge=0, le=100)


class ZappingAnalysisResult(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schemaVersion: Literal["vibe-control-zapping-analysis-v2"] = (
        "vibe-control-zapping-analysis-v2"
    )
    generatedAt: str = Field(
        min_length=1,
        description="ISO 8601 timestamp generated by the model for this analysis.",
    )
    transcriptSummary: str | None = None
    productContextSummary: str | None = None
    operationIntent: str | None = None
    storyCandidates: list[ZappingAnalysisStoryCandidate] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)
