"""Firebase Functions entrypoint for AI Studio backend."""

from triggers import adk_artifact_signed_url  # noqa: F401
from triggers import adk_artifact_storage  # noqa: F401
from triggers import adk_invoke_requests  # noqa: F401
from triggers import auth_email_link  # noqa: F401
from triggers import google_workspace_oauth  # noqa: F401
from triggers import github_oauth  # noqa: F401
from triggers import guide_assistant  # noqa: F401
from triggers import member_user_requests  # noqa: F401
from triggers import research_completion_email  # noqa: F401
from triggers import saas_onboarding  # noqa: F401
from triggers import transactional_email_requests  # noqa: F401
from triggers import verify_ai_studio_spreadsheet  # noqa: F401
from triggers import web_crawl_requests  # noqa: F401
from triggers.adk_artifact_signed_url import get_artifact_signed_url  # noqa: F401
from triggers.adk_artifact_storage import on_adk_artifact_object_finalized  # noqa: F401
from triggers.adk_invoke_requests import on_adk_invoke_request_created  # noqa: F401
from triggers.auth_email_link import dev_admin_sign_in  # noqa: F401
from triggers.auth_email_link import send_admin_sign_in_link  # noqa: F401
from triggers.google_workspace_oauth import connect_google_workspace  # noqa: F401
from triggers.google_workspace_oauth import disconnect_google_workspace  # noqa: F401
from triggers.google_workspace_oauth import get_google_workspace_connection  # noqa: F401
from triggers.google_workspace_oauth import list_google_drive_folder  # noqa: F401
from triggers.google_workspace_oauth import test_google_drive_folder  # noqa: F401
from triggers.github_oauth import connect_github  # noqa: F401
from triggers.github_oauth import disconnect_github  # noqa: F401
from triggers.github_oauth import get_github_connection  # noqa: F401
from triggers.github_oauth import get_github_repository  # noqa: F401
from triggers.github_oauth import list_github_merged_pull_requests  # noqa: F401
from triggers.github_oauth import list_github_repositories  # noqa: F401
from triggers.guide_assistant import ask_en_aistudio_guide  # noqa: F401
from triggers.member_user_requests import on_member_user_create_request_created  # noqa: F401
from triggers.member_user_requests import on_member_user_delete_request_created  # noqa: F401
from triggers.member_user_requests import on_member_user_update_request_created  # noqa: F401
from triggers.saas_onboarding import on_saas_onboarding_request_created  # noqa: F401
from triggers.transactional_email_requests import on_transactional_email_request_created  # noqa: F401
from triggers.verify_ai_studio_spreadsheet import verify_ai_studio_spreadsheet  # noqa: F401
from triggers.web_crawl_requests import web_crawl_request_handler  # noqa: F401
